set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR riscv32)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(DBGC_WCH_TOOLCHAIN_ROOT "$ENV{HOME}/.local/share/DBG-C/toolchains/MRS-2.4.0/RISC-V Embedded GCC12/bin" CACHE PATH "MounRiver RISC-V GCC 12 toolchain bin directory")
set(CMAKE_C_COMPILER "${DBGC_WCH_TOOLCHAIN_ROOT}/riscv-wch-elf-gcc")
set(CMAKE_ASM_COMPILER "${DBGC_WCH_TOOLCHAIN_ROOT}/riscv-wch-elf-gcc")
set(CMAKE_AR "${DBGC_WCH_TOOLCHAIN_ROOT}/riscv-wch-elf-ar")
set(CMAKE_OBJCOPY "${DBGC_WCH_TOOLCHAIN_ROOT}/riscv-wch-elf-objcopy")
set(CMAKE_OBJDUMP "${DBGC_WCH_TOOLCHAIN_ROOT}/riscv-wch-elf-objdump")
set(CMAKE_SIZE "${DBGC_WCH_TOOLCHAIN_ROOT}/riscv-wch-elf-size")
set(CMAKE_C_FLAGS_INIT "-march=rv32imac -mabi=ilp32 -mcmodel=medany")
set(CMAKE_ASM_FLAGS_INIT "-march=rv32imac -mabi=ilp32 -mcmodel=medany -D__ASSEMBLER__")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-march=rv32imac -mabi=ilp32 -mcmodel=medany")
