set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR riscv32)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
if(NOT DEFINED DBGC_WCH_TOOLCHAIN_ROOT)
    if(DEFINED ENV{DBGC_WCH_TOOLCHAIN_ROOT})
        set(DBGC_WCH_TOOLCHAIN_ROOT "$ENV{DBGC_WCH_TOOLCHAIN_ROOT}" CACHE PATH "WCH RISC-V toolchain bin directory")
    else()
        message(FATAL_ERROR "Set DBGC_WCH_TOOLCHAIN_ROOT or invoke the build_poc1.py tool, which resolves the toolchain from PATH")
    endif()
endif()
if(CMAKE_HOST_WIN32)
    set(DBGC_WCH_TOOL_SUFFIX ".exe")
else()
    set(DBGC_WCH_TOOL_SUFFIX "")
endif()
set(CMAKE_C_COMPILER "${DBGC_WCH_TOOLCHAIN_ROOT}/riscv-wch-elf-gcc${DBGC_WCH_TOOL_SUFFIX}")
set(CMAKE_ASM_COMPILER "${DBGC_WCH_TOOLCHAIN_ROOT}/riscv-wch-elf-gcc${DBGC_WCH_TOOL_SUFFIX}")
set(CMAKE_AR "${DBGC_WCH_TOOLCHAIN_ROOT}/riscv-wch-elf-ar${DBGC_WCH_TOOL_SUFFIX}")
set(CMAKE_RANLIB "${DBGC_WCH_TOOLCHAIN_ROOT}/riscv-wch-elf-ranlib${DBGC_WCH_TOOL_SUFFIX}")
set(CMAKE_OBJCOPY "${DBGC_WCH_TOOLCHAIN_ROOT}/riscv-wch-elf-objcopy${DBGC_WCH_TOOL_SUFFIX}")
set(CMAKE_OBJDUMP "${DBGC_WCH_TOOLCHAIN_ROOT}/riscv-wch-elf-objdump${DBGC_WCH_TOOL_SUFFIX}")
set(CMAKE_SIZE "${DBGC_WCH_TOOLCHAIN_ROOT}/riscv-wch-elf-size${DBGC_WCH_TOOL_SUFFIX}")
set(CMAKE_C_FLAGS_INIT "-march=rv32imac -mabi=ilp32 -mcmodel=medany")
set(CMAKE_ASM_FLAGS_INIT "-march=rv32imac -mabi=ilp32 -mcmodel=medany -D__ASSEMBLER__")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-march=rv32imac -mabi=ilp32 -mcmodel=medany")
