#ifndef DBG_C_TX_USER_H
#define DBG_C_TX_USER_H
#define TX_MAX_PRIORITIES 32
#define TX_MINIMUM_STACK 512
#define TX_TIMER_THREAD_STACK_SIZE 512
#define TX_TIMER_THREAD_PRIORITY 1
#define TX_TIMER_TICKS_PER_SECOND 1000UL
#endif
